version: '3'
services:
  # Declaration of the MYSQL container that will hold the database in Docker
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    container_name: leanTech_db
    volumes:
     - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes: 
      - db-data:/var/lib/mysql
    
  # This is the declaration of the container for the main backend app and the connection
  #  to the MYSQL container
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    container_name: leanTech_bg
    depends_on:
      - mysql
    env_file: 
      - .env
    
volumes: 
  db-data: